name: Get Artifacts

on:
  workflow_dispatch:

jobs:
  print-artifacts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R