name: Save Commit Hash 

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'ID for the workflow run'
        required: true
        default: 'default-id'

jobs:
  save-commit-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current commit hash
        run: echo "id, version \n ${{ inputs.id }}, ${{ github.sha }}" > commit_hash.txt

      - name: Upload commit hash artifact
        uses: actions/upload-artifact@v4
        with:
            name: run-info
            path: commit_hash.txt
