name: Save Commit Hash 

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'ID for the workflow run'
        required: true
        default: 'default-id'

jobs:
  save-commit-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current commit hash
        run: echo "${{ inputs.id }}, ${{ github.sha }}" >> ${{ inputs.id }}.txt

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: site-versions
          path: site-versions/
        
      - name: Get Revision info
        run: |
          echo "Sha: ${{ github.sha }}" > site-versions/${{ inputs.id }}.txt
          echo "Ref: ${{ github.ref }}" >> site-versions/${{ inputs.id }}.txt
          echo "Ref name: ${{ github.ref_name }}" >> site-versions/${{ inputs.id }}.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: site-versions
            path: site-versions/*
